version: "3.7"

services:
  web:
    image: ghcr.io/itchysats/itchysats/taker:0.3.2@sha256:f119008fa0ec10a028290272a2c42974fe70863a3e88b030510e1f5a5af8db23
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --maker=mainnet.itchysats.network:9999
      - --maker-id=7e35e34801e766a6a29ecb9e22810ea4e3476c2b37bf75882edf94a68b1d9607
      - mainnet
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
