version: "3.7"

services:
  web:
    image: ghcr.io/itchysats/itchysats/taker:0.4.14@sha256:ae760e9685144d18c4ec11af05024fb93f8b70ad093efd640e427d9c0bc9d6b1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $BITCOIN_NETWORK
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
