version: "3.7"

services:
  web:
    # TODO: get latest release from https://github.com/itchysats/itchysats/pkgs/container/itchysats%2Ftaker
    image: ghcr.io/itchysats/itchysats/taker:0.2.0@sha256:2272501cf986b0ac7cfad55c0320cf1f2f036871079ad518017cd49de5f0c4e3
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --maker=mainnet.itchysats.network:9999
      - --maker-id=7e35e34801e766a6a29ecb9e22810ea4e3476c2b37bf75882edf94a68b1d9607
      - --log-level=trace
      - mainnet
#      once synced drop this commit
#      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT
    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP



