version: "3.7"

services:
  web:
    image: ghcr.io/itchysats/itchysats/taker:0.4.17@sha256:fb5a88d34a4783bc49c2ce74cac4fd1098b5247921fdeb0560c54123f503b335
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $BITCOIN_NETWORK
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
