version: "3.7"

services:
  web:
    image: ghcr.io/itchysats/itchysats/taker:0.4.19@sha256:93a1f7adcb5a4ed88c365401775e0ef39a20647199ba771ae5cb07d87a3bab58
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $BITCOIN_NETWORK
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT
    environment:
      - ITCHYSATS_ENV=umbrel

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
