version: "3.7"

services:
  web:
    image: ghcr.io/itchysats/itchysats/taker:0.5.0@sha256:884f2f23756e67dd418aaf1aa2c5fcaf385bec6f37dc8412a02ab870da2168b5
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_ITCHYSATS_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $BITCOIN_NETWORK
      - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
